//
// Created by olesg on 9/11/2021.
//
#pragma  	once
#ifndef 	INC_8BITEMU_SOURCES_CHIP8_CONFIG_H_
#define 	INC_8BITEMU_SOURCES_CHIP8_CONFIG_H_
#define  	CHIP8_MEMORY_SIZE 				4096
#define  	CHIP8_WIDTH 					64
#define  	CHIP8_HEIGHT 					32
#define  	CHIP8_WINDOW_MULTIPLIER 		10
#define		EMULATOR_WINDOW_TITLE 			"EMUL8"
#define 	CHIP8_TOTAL_DATA_REGISTERS 		18
#define 	CHIP8_TOTAL_STACK_DEPTH			16
#define		CHIP8_TOTAL_KEYS				16
#endif //INC_8BITEMU_SOURCES_CHIP8_CONFIG_H_
